In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

In [2]:
df95 = pd.read_csv('../data/resultados/sensibilidad/resume0;95.csv', sep=';')
df95.head()

,Day,Configuracion,NOperations,SOperations,TotalOperations,ConfigNorm
0,2018-01-01 02:30:00,NORTE,1,0,1,1
1,2018-01-01 03:00:00,NORTE,1,0,1,1
2,2018-01-01 03:30:00,NORTE,2,0,2,1
3,2018-01-01 04:00:00,NORTE,2,0,2,1
4,2018-01-01 04:30:00,NORTE,3,0,3,1

In [3]:
# Generamos la nueva columna obteniendo los datos a partir de la sensibilidad
configuration_colum = []
for index, row in df95.iterrows():
    if row['ConfigNorm'] == 2: # Existe conflicto
        if row['NOperations'] > row['SOperations']:
            configuration_colum.append("NORTE")
        elif row['SOperations'] > row['NOperations']:
            configuration_colum.append("SUR")
        else:
            configuration_colum.append(np.nan)
    else:
        configuration_colum.append(row["Configuracion"])

df95["Configuracion"] = configuration_colum

In [4]:
#Comprobamos si tenemos valores desconocidos con el procesamiento anterior
print(df95.isnull().sum())
print(df95.shape)

Day                 0
Configuracion      22
NOperations         0
SOperations         0
TotalOperations     0
ConfigNorm          0
dtype: int64
(36743, 6)

In [5]:
df95['Configuracion'] = df95['Configuracion'].fillna(method='ffill') #Completamos los valores restantes

In [6]:
#Comprobamos si tenemos valores desconocidos con el procesamiento anterior
print(df95.isnull().sum())
print(df95.shape)

Day                0
Configuracion      0
NOperations        0
SOperations        0
TotalOperations    0
ConfigNorm         0
dtype: int64
(36743, 6)

In [7]:
dictionary = {}
for index, row in df95.iterrows(): # Obtenemos la configuracion existente a una determinada fecha en intervalos de 30 mins
    dictionary[row['Day']] = row['Configuracion']

In [8]:
# Comprobamos que tenemos todas las fechas y no nos hemos dejado ninguna
print(len(dictionary)) 
print(df95["Day"].unique().shape[0])

36743
36743

In [9]:
df = pd.read_csv("../data/datasets/cleanData.csv" , sep=";")
df.head()

,id_leg,runway,operation1,operation2,hexid,callsign,time_stamp,altitude,ground_speed,vertical_rate,type,origin,destination,part_date_utc,valid_time,tmp,dew_pt,rel_hum,wind_dir,win_sp,wind_gust,visib,press,sky_lvl,rain,snow,drizzle,fog,time_class,day_week,month,time_ref,id_legNORM,operationNORM,hexidNORM,callsignNORM,typeNORM,originNORM,destinationNORM,operation_Landing,operation_TakeOff,runway_14L,runway_14R,runway_18L,runway_18R,runway_32L,runway_32R,runway_36L,runway_36R,runwayNORM
0,fff052a,32R,Landing,Landing,342210,IBE3329,2018-01-01 02:43:52,1625.0,142.0,-768.0,A321,DSS,MAD,2018-01-01,2018-01-01 02:30:00,7.0,0.0,61.017,250.0,20.372,0.000000,10.0,1030.0,10.0,0.0,0.0,0.0,0.0,2.0,1.0,1.0,6.0,733513,0,483,6920,22,186,268,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,5
1,ffe804b,32R,Landing,Landing,3424D0,AEA026,2018-01-01 03:24:37,1850.0,137.0,-768.0,A332,VVI,MAD,2018-01-01,2018-01-01 03:00:00,7.0,-1.0,56.724,250.0,25.928,44.447962,10.0,1030.0,10.0,0.0,0.0,0.0,0.0,3.0,1.0,1.0,7.0,733498,0,515,246,23,664,268,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,5
2,ffe725d,32R,Landing,Landing,34530C,AEA042,2018-01-01 03:38:12,2200.0,156.0,-832.0,B788,EZE,MAD,2018-01-01,2018-01-01 03:30:00,7.0,-1.0,56.724,230.0,16.668,0.000000,10.0,1031.0,10.0,0.0,0.0,0.0,0.0,3.0,1.0,1.0,8.0,733495,0,814,262,67,212,268,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,5
3,ffea19d,32R,Landing,Landing,344211,AEA058,2018-01-01 03:57:16,1862.5,143.0,-640.0,A332,GRU,MAD,2018-01-01,2018-01-01 03:30:00,7.0,-1.0,56.724,230.0,16.668,0.000000,10.0,1031.0,10.0,0.0,0.0,0.0,0.0,3.0,1.0,1.0,8.0,733501,0,625,277,23,254,268,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,5
4,ffe781e,32R,Landing,Landing,3422CA,AEA046,2018-01-01 04:05:21,2000.0,136.0,-640.0,A332,MVD,MAD,2018-01-01,2018-01-01 04:00:00,5.0,0.0,70.063,160.0,12.964,0.000000,10.0,1031.0,10.0,0.0,0.0,0.0,0.0,4.0,1.0,1.0,9.0,733496,0,491,268,23,421,268,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,5

In [10]:
# Generamos la nueva columna en funcion de la fecha del vuelo y la configuracion en ese momento segun el diccionario anterior
runway_configuration = []
for index, row in df.iterrows():
    runway_configuration.append(dictionary[row['valid_time']])

In [11]:
# Añadimos la nueva columna y guardamos el dataframe
df['Configuration'] = runway_configuration

In [12]:
df.to_csv('../data/datasets/rawDataWithConfiguration.csv', sep=';' , index=False)